### ISSUE TITLE
Convert Ensembl Data 

### ISSUE THREAD

**Issue by venuraherath** [csoderlund/SyMAP#1]
I am trying to use SYMAP to do self synteny on potato genome. I am using ENSEMBL plants for data retrieval given the fact that it is much better curated for the genome of interest compared to NCBI.  
Do you have a script to generate input files from ENSEMBL files like you have for NCBI?
I appreciate if you can help me with this.

Just in case , here is the link to gff files:[ ftp://ftp.ensemblgenomes.org/pub/plants/release-45/gff3/solanum_tuberosum]( ftp://ftp.ensemblgenomes.org/pub/plants/release-45/gff3/solanum_tuberosum) and sequences[ ftp://ftp.ensemblgenomes.org/pub/plants/release-45/fasta/solanum_tuberosum/dna/]( ftp://ftp.ensemblgenomes.org/pub/plants/release-45/fasta/solanum_tuberosum/dna/) of the potato genome.

Thank you so much,

**Comment by csoderlund** [comment]
scripts/ConvertEnsembl was added in v5.0
