### ISSUE TITLE
Unable to connect to the mysql database on localhost; are username and password correct?

### ISSUE THREAD

**Issue by LorenaDerezanin** [csoderlund/SyMAP#2]
Hi, I'm trying to run the latest release of `symap` - `5.0.2` on Manjaro Linux. I've installed `mariadb` as an implementation of `mysql`, because `mysql` is not supported on Arch anymore.

I've created a user `symap` with the password `symap` in `mysql` as suggested in the [System Guide](http://www.agcol.arizona.edu/software/symap/doc/SystemGuide.html#mysql), and this is how my `symap.conf` looks like:
```ini
# SyMAP configuration parameters file
#
# Note, rows preceded by # are ignored.

# MySQL database name (e.g symap), server (e.g. localhost), admin and public access (client) info
# See http://www.agcol.arizona.edu/software/symap/doc/SystemGuide.html#params for details.
# Leave user and password empty if you don't have MySQL on your system and want to use the built-in mySQL
db_name             = symap
db_server           = localhost
db_adminuser        = symap
db_adminpasswd      = symap
db_clientuser       = symap
db_clientpasswd     = symap

######################
# For the number of CPUs (threads, processors) to be used for computation, 
# any of the following will work:
# 1. From the interface, change the number in the nCPUs text box 
# 2. Use the command line option "-p N" where N is the number of CPUs to use.
# 3. Use the 'nCPUs' parameter below by uncommenting the line and entering number.
nCPUs = 4
```

However, when I try to run `./symap`, I get the following error:
```
$ ./symap
>>>> SyMAP with no 3D (2048m) <<<<

SyMAP Version v5.0.2 (24-Feb-20)
Java Version 1.8.0_242, mem: 1820M
Reading from file symap.config
Max CPUs 4 (out of 4 available)
SyMAP database symap
Unable to connect to the mysql database on localhost; are username and password correct?
```

Even though starting mysql as follows works fine:
```bash
$ mysql -u symap -h localhost --password=symap
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 15
Server version: 10.4.12-MariaDB Arch Linux

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

What am I doing wrong? :disappointed_relieved:

**Comment by csoderlund** [comment]
Lori,

I also have MariaDB on linux and cannot reproduce this error, no matter
what I try.
The only thing I can think of is that the userid/password is for read-only.
Would you try from mysql: create database symap;
Does that work? If so, I don't know what to suggest.... I can give you a
jar file that has the SQL message printed out, which may tell us
something...

I saw your next email and I'll get back to you on it, but building symap
yourself should not fix this problem.

Cari

**Comment by LorenaDerezanin** [comment]
Hi Cari,

Thanks for getting back to me. In order to get down to the root of the problem, I cloned `SyMAP` and added a `e.printStackTrace()` here https://github.com/csoderlund/SyMAP/blob/8a1d8de39813fa10d7bc754a2c1ad3ea330e0923/java/src/symap/pool/DatabaseUser.java#L353

to see what the actual issue was.

This gave the following output:
```java
>>>> SyMAP with no 3D (2048m) <<<<

SyMAP Version v5.0.2 (24-Feb-20)
Java Version 1.8.0_242, mem: 1820M
Reading from file symap.config
SyMAP database symap
Unable to connect to the mysql database on localhost; are username and password correct?
java.sql.SQLException: Unknown initial character set index '224' received from server. Initial client character set can be forced via the 'characterEncoding' property.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:910)
	at com.mysql.jdbc.Connection.configureClientCharacterSet(Connection.java:2412)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:4139)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2789)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at symap.pool.DatabaseUser.checkHost(DatabaseUser.java:344)
	at symap.pool.DatabaseUser.createDatabase(DatabaseUser.java:368)
	at symap.projectmanager.common.ProjectManagerFrameCommon.getDatabaseReader(ProjectManagerFrameCommon.java:203)
	at symap.projectmanager.common.ProjectManagerFrameCommon.initialize(ProjectManagerFrameCommon.java:216)
	at symap.projectmanager.common.ProjectManagerFrameCommon.<init>(ProjectManagerFrameCommon.java:118)
	at symapCE.ProjectManagerFrame.<init>(ProjectManagerFrame.java:18)
	at symapCE.ProjectManagerFrame.main(ProjectManagerFrame.java:70)
```
After googling for this error message, it seems that the right solution would be to use the most recent connector library for MySQL in `SyMAP`: https://stackoverflow.com/a/50855623

I'm guessing you couldn't reproduce the error because you're possibly using an older version of MariaDB than I am. I'm using `10.4.12`.

As a workaround, I just added the following lines to `/etc/my.cnf`:
```ini
[mysqld]
character-set-server=utf8mb4
```

After restarting MariaDB with `systemctl restart mariadb`, and starting `symap` again, it worked! :tada: 

So updating the MySQL connector libraries could help, and consider logging the exception when catching it, as suggested above :innocent:

**Comment by csoderlund** [comment]
Lori,
I really appreciate you letting me know! I will do both suggestions.
Thank you!
Cari

**Comment by csoderlund** [comment]
With v5.0.3, the Java error message is printed when it cannot connect. The documentation describes how the problem can be fixed when using later versions of MariaDB with Manjaro Linux.
