### ISSUE TITLE
Export alignment computation

### ISSUE THREAD

**Issue by dabitz** [csoderlund/SyMAP#4]
Hi Cori,

Thanks for this amazing software. Is it possible to share or export alignment synteny computations to another database or symap user without redoing all the computations again?

Best
André

**Comment by csoderlund** [comment]
Andre,

You can dump the contents of the SyMAP database with mysqldump, send it to
another lab and they can load it into their MySQL.
You would also need to send them the /data directory; then they can
download symap, replace the data directory with the one you sent.
Then they can use symap to view your alignments. Would that work for what
you need?

Cari

**Comment by dabitz** [comment]
Thanks a lot! It seems to be working properly!
