### ISSUE TITLE
Error while trying self synteny in SyMAP v5.4

### ISSUE THREAD

**Issue by dabitz** [csoderlund/SyMAP#6]
I keep getting this error when trying self synteny, synteny against a different genome works fine.

>>> Start Alignment&Synteny
Append to log file: logs/Dregia_to_Dregia/symap.log (Length 19.4k)
Log alignments in directory: logs/Dregia_to_Dregia

>>> Starting Dregia to self     07-Jul-23 13:55:15
Use default parameters
Warning: 153 alignment files exist - using existing files ...
   If not correct, remove data/seq_results/Dregia_to_Dregia and re-align.
Finding good hits for Dregia and Dregia
Loading annotations
    33761 Dregia genes            
Alignment files in data/seq_results/Dregia_to_Dregia/align/
Scan files to create candidate genes from hits
     2262 scanned NUCMER Dregia_f5.Dregia_f2.mum           
     1918 scanned NUCMER Dregia_f6.Dregia_f10.mum           
     2859 scanned NUCMER Dregia_f16.Dregia_f13.mum           
     3017 scanned NUCMER Dregia_f9.Dregia_f7.mum           
     3110 scanned NUCMER Dregia_f16.Dregia_f11.mum           
     3406 scanned NUCMER Dregia_f2.Dregia_f1.mum           
     2744 scanned NUCMER Dregia_f3.Dregia_f1.mum           
     2494 scanned NUCMER Dregia_f8.Dregia_f13.mum           
     2047 scanned NUCMER Dregia_f9.Dregia_f2.mum           
     3619 scanned NUCMER Dregia_f13.Dregia_f1.mum           
     3137 scanned NUCMER Dregia_f7.Dregia_f6.mum           
     3156 scanned NUCMER Dregia_f4.Dregia_f12.mum           
     2469 scanned NUCMER Dregia_f3.Dregia_f2.mum           
     1953 scanned NUCMER Dregia_f2.Dregia_f14.mum           
     2158 scanned NUCMER Dregia_f6.Dregia_f4.mum           
     3353 scanned NUCMER Dregia_f8.Dregia_f7.mum           
     2894 scanned NUCMER Dregia_f3.Dregia_f11.mum           
     3000 scanned NUCMER Dregia_f8.Dregia_f6.mum           
     2760 scanned NUCMER Dregia_f3.Dregia_f15.mum           
     2919 scanned NUCMER Dregia_f8.Dregia_f14.mum           
     4792 scanned NUCMER Dregia_f14.Dregia_f12.mum           
     2015 scanned NUCMER Dregia_f6.Dregia_f15.mum           
     2732 scanned NUCMER Dregia_f7.Dregia_f14.mum           
     2189 scanned NUCMER Dregia_f7.Dregia_f1.mum           
     3573 scanned NUCMER Dregia_f16.Dregia_f14.mum           
     3067 scanned NUCMER Dregia_f13.Dregia_f12.mum           
     2148 scanned NUCMER Dregia_f17.Dregia_f1.mum           
     2649 scanned NUCMER Dregia_f13.Dregia_f11.mum           
     2727 scanned NUCMER Dregia_f4.Dregia_f17.mum           
     2231 scanned NUCMER Dregia_f9.Dregia_f4.mum           
     2158 scanned NUCMER Dregia_f17.Dregia_f10.mum           
     2768 scanned NUCMER Dregia_f5.Dregia_f13.mum           
     2805 scanned NUCMER Dregia_f5.Dregia_f15.mum           
     2621 scanned NUCMER Dregia_f15.Dregia_f12.mum           
     4297 scanned NUCMER Dregia_f4.Dregia_f3.mum           
     2163 scanned NUCMER Dregia_f6.Dregia_f3.mum           
     2383 scanned NUCMER Dregia_f6.Dregia_f14.mum           
     2456 scanned NUCMER Dregia_f3.Dregia_f17.mum           
     2383 scanned NUCMER Dregia_f5.Dregia_f10.mum           
     1767 scanned NUCMER Dregia_f2.Dregia_f11.mum           
     2377 scanned NUCMER Dregia_f8.Dregia_f17.mum           
     2511 scanned NUCMER Dregia_f8.Dregia_f3.mum           
     2946 scanned NUCMER Dregia_f4.Dregia_f10.mum           
     2193 scanned NUCMER Dregia_f9.Dregia_f1.mum           
     2253 scanned NUCMER Dregia_f9.Dregia_f5.mum           
     3244 scanned NUCMER Dregia_f15.Dregia_f14.mum           
     2234 scanned NUCMER Dregia_f9.Dregia_f11.mum           
     2481 scanned NUCMER Dregia_f7.Dregia_f4.mum           
     1938 scanned NUCMER Dregia_f6.Dregia_f17.mum           
     2230 scanned NUCMER Dregia_f15.Dregia_f10.mum           
     2465 scanned NUCMER Dregia_f9.Dregia_f16.mum           
     2285 scanned NUCMER Dregia_f6.Dregia_f5.mum           
     3161 scanned NUCMER Dregia_f15.Dregia_f13.mum           
     2910 scanned NUCMER Dregia_f16.Dregia_f1.mum           
     1706 scanned NUCMER Dregia_f2.Dregia_f17.mum           
     2700 scanned NUCMER Dregia_f5.Dregia_f3.mum           
     1870 scanned NUCMER Dregia_f7.Dregia_f2.mum           
     2457 scanned NUCMER Dregia_f7.Dregia_f5.mum           
     3186 scanned NUCMER Dregia_f3.Dregia_f14.mum           
     2535 scanned NUCMER Dregia_f5.Dregia_f11.mum           
     3693 scanned NUCMER Dregia_f3.Dregia_f16.mum           
     2638 scanned NUCMER Dregia_f5.Dregia_f4.mum           
     4789 scanned NUCMER Dregia_f14.Dregia_f13.mum           
     2659 scanned NUCMER Dregia_f2.Dregia_f13.mum           
     3437 scanned NUCMER Dregia_f14.Dregia_f1.mum           
     2631 scanned NUCMER Dregia_f7.Dregia_f16.mum           
     2291 scanned NUCMER Dregia_f7.Dregia_f3.mum           
     3347 scanned NUCMER Dregia_f4.Dregia_f11.mum           
     3227 scanned NUCMER Dregia_f17.Dregia_f16.mum           
     2714 scanned NUCMER Dregia_f3.Dregia_f10.mum           
     2620 scanned NUCMER Dregia_f13.Dregia_f10.mum           
     2993 scanned NUCMER Dregia_f17.Dregia_f15.mum           
     2393 scanned NUCMER Dregia_f17.Dregia_f13.mum           
     2480 scanned NUCMER Dregia_f5.Dregia_f1.mum           
     2284 scanned NUCMER Dregia_f9.Dregia_f3.mum           
     2413 scanned NUCMER Dregia_f10.Dregia_f1.mum           
     2738 scanned NUCMER Dregia_f8.Dregia_f12.mum           
     1930 scanned NUCMER Dregia_f2.Dregia_f12.mum           
     2712 scanned NUCMER Dregia_f4.Dregia_f15.mum           
     2724 scanned NUCMER Dregia_f9.Dregia_f14.mum           
     2118 scanned NUCMER Dregia_f6.Dregia_f13.mum           
     2592 scanned NUCMER Dregia_f7.Dregia_f12.mum           
     2628 scanned NUCMER Dregia_f9.Dregia_f12.mum           
     2162 scanned NUCMER Dregia_f7.Dregia_f17.mum           
     3137 scanned NUCMER Dregia_f14.Dregia_f10.mum           
     2036 scanned NUCMER Dregia_f2.Dregia_f16.mum           
     2944 scanned NUCMER Dregia_f3.Dregia_f12.mum           
     4344 scanned NUCMER Dregia_f4.Dregia_f16.mum           
     2896 scanned NUCMER Dregia_f4.Dregia_f13.mum           
     2311 scanned NUCMER Dregia_f9.Dregia_f15.mum           
     1739 scanned NUCMER Dregia_f2.Dregia_f15.mum           
     2705 scanned NUCMER Dregia_f12.Dregia_f1.mum           
     2157 scanned NUCMER Dregia_f11.Dregia_f1.mum           
     2191 scanned NUCMER Dregia_f9.Dregia_f17.mum           
     2252 scanned NUCMER Dregia_f7.Dregia_f15.mum           
     2357 scanned NUCMER Dregia_f15.Dregia_f1.mum           
     2486 scanned NUCMER Dregia_f7.Dregia_f11.mum           
     3644 scanned NUCMER Dregia_f12.Dregia_f10.mum           
     2711 scanned NUCMER Dregia_f8.Dregia_f16.mum           
     2138 scanned NUCMER Dregia_f7.Dregia_f10.mum           
     1926 scanned NUCMER Dregia_f6.Dregia_f1.mum           
     2552 scanned NUCMER Dregia_f4.Dregia_f2.mum           
     2857 scanned NUCMER Dregia_f9.Dregia_f8.mum           
     2515 scanned NUCMER Dregia_f8.Dregia_f4.mum           
     1787 scanned NUCMER Dregia_f6.Dregia_f2.mum           
     2528 scanned NUCMER Dregia_f8.Dregia_f15.mum           
     2976 scanned NUCMER Dregia_f5.Dregia_f12.mum           
     3731 scanned NUCMER Dregia_f12.Dregia_f11.mum           
     2710 scanned NUCMER Dregia_f5.Dregia_f16.mum           
     2562 scanned NUCMER Dregia_f8.Dregia_f11.mum           
     2060 scanned NUCMER Dregia_f9.Dregia_f10.mum           
     2743 scanned NUCMER Dregia_f3.Dregia_f13.mum           
     2543 scanned NUCMER Dregia_f16.Dregia_f10.mum           
     2301 scanned NUCMER Dregia_f7.Dregia_f13.mum           
     3042 scanned NUCMER Dregia_f5.Dregia_f14.mum           
     2091 scanned NUCMER Dregia_f9.Dregia_f6.mum           
     2307 scanned NUCMER Dregia_f15.Dregia_f11.mum           
     3067 scanned NUCMER Dregia_f16.Dregia_f12.mum           
     2663 scanned NUCMER Dregia_f17.Dregia_f14.mum           
     3836 scanned NUCMER Dregia_f16.Dregia_f15.mum           
     2355 scanned NUCMER Dregia_f8.Dregia_f1.mum           
     4054 scanned NUCMER Dregia_f4.Dregia_f14.mum           
     3167 scanned NUCMER Dregia_f4.Dregia_f1.mum           
     2258 scanned NUCMER Dregia_f9.Dregia_f13.mum           
     1961 scanned NUCMER Dregia_f6.Dregia_f11.mum           
     4111 scanned NUCMER Dregia_f14.Dregia_f11.mum           
     2261 scanned NUCMER Dregia_f17.Dregia_f11.mum           
     2468 scanned NUCMER Dregia_f11.Dregia_f10.mum           
     4152 scanned NUCMER Dregia_f5.Dregia_f17.mum           
     2159 scanned NUCMER Dregia_f8.Dregia_f10.mum           
     1659 scanned NUCMER Dregia_f2.Dregia_f10.mum           
     2497 scanned NUCMER Dregia_f17.Dregia_f12.mum           
     2323 scanned NUCMER Dregia_f6.Dregia_f16.mum           
     2158 scanned NUCMER Dregia_f8.Dregia_f2.mum           
     2384 scanned NUCMER Dregia_f6.Dregia_f12.mum           
     2517 scanned NUCMER Dregia_f8.Dregia_f5.mum           
     2375 scanned NUCMER self.Dregia_f5.mum           
     2254 scanned NUCMER self.Dregia_f4.mum           
     1605 scanned NUCMER self.Dregia_f11.mum           
     1791 scanned NUCMER self.Dregia_f3.mum           
     1266 scanned NUCMER self.Dregia_f9.mum           
     1924 scanned NUCMER self.Dregia_f12.mum           
     2509 scanned NUCMER self.Dregia_f14.mum           
     1776 scanned NUCMER self.Dregia_f13.mum           
      928 scanned NUCMER self.Dregia_f2.mum           
     1628 scanned NUCMER self.Dregia_f15.mum           
     2189 scanned NUCMER self.Dregia_f16.mum           
     1454 scanned NUCMER self.Dregia_f10.mum           
     1399 scanned NUCMER self.Dregia_f6.mum           
     1357 scanned NUCMER self.Dregia_f7.mum           
     1602 scanned NUCMER self.Dregia_f1.mum           
     1397 scanned NUCMER self.Dregia_f17.mum           
     1677 scanned NUCMER self.Dregia_f8.mum           
   391554 Total scanned hits           
   377712 Total accepted hits           
     1035 Large hits (> 50000)  5333 Split            
Scan files to cluster and filter hits
     1927 clustered Dregia_f5.Dregia_f2.mum           
     1607 clustered Dregia_f6.Dregia_f10.mum           
     2374 clustered Dregia_f16.Dregia_f13.mum           
     2278 clustered Dregia_f9.Dregia_f7.mum           
     2287 clustered Dregia_f16.Dregia_f11.mum           
     2377 clustered Dregia_f2.Dregia_f1.mum           
     2011 clustered Dregia_f3.Dregia_f1.mum           
     2069 clustered Dregia_f8.Dregia_f13.mum           
     1729 clustered Dregia_f9.Dregia_f2.mum           
     2727 clustered Dregia_f13.Dregia_f1.mum           
     2294 clustered Dregia_f7.Dregia_f6.mum           
     2233 clustered Dregia_f4.Dregia_f12.mum           
     1938 clustered Dregia_f3.Dregia_f2.mum           
     1632 clustered Dregia_f2.Dregia_f14.mum           
     1660 clustered Dregia_f6.Dregia_f4.mum           
     2498 clustered Dregia_f8.Dregia_f7.mum           
     2096 clustered Dregia_f3.Dregia_f11.mum           
     2192 clustered Dregia_f8.Dregia_f6.mum           
     2161 clustered Dregia_f3.Dregia_f15.mum           
     2222 clustered Dregia_f8.Dregia_f14.mum           
     3159 clustered Dregia_f14.Dregia_f12.mum           
     1622 clustered Dregia_f6.Dregia_f15.mum           
     2141 clustered Dregia_f7.Dregia_f14.mum           
     1764 clustered Dregia_f7.Dregia_f1.mum           
     2633 clustered Dregia_f16.Dregia_f14.mum           
     2619 clustered Dregia_f13.Dregia_f12.mum           
     1840 clustered Dregia_f17.Dregia_f1.mum           
     2164 clustered Dregia_f13.Dregia_f11.mum           
     2062 clustered Dregia_f4.Dregia_f17.mum           
     1806 clustered Dregia_f9.Dregia_f4.mum           
     1877 clustered Dregia_f17.Dregia_f10.mum           
     2316 clustered Dregia_f5.Dregia_f13.mum           
     2289 clustered Dregia_f5.Dregia_f15.mum           
     2226 clustered Dregia_f15.Dregia_f12.mum           
     3013 clustered Dregia_f4.Dregia_f3.mum           
     1698 clustered Dregia_f6.Dregia_f3.mum           
     1832 clustered Dregia_f6.Dregia_f14.mum           
     1911 clustered Dregia_f3.Dregia_f17.mum           
     1974 clustered Dregia_f5.Dregia_f10.mum           
     1482 clustered Dregia_f2.Dregia_f11.mum           
     1998 clustered Dregia_f8.Dregia_f17.mum           
     1917 clustered Dregia_f8.Dregia_f3.mum           
     2268 clustered Dregia_f4.Dregia_f10.mum           
     1814 clustered Dregia_f9.Dregia_f1.mum           
     1977 clustered Dregia_f9.Dregia_f5.mum           
     2560 clustered Dregia_f15.Dregia_f14.mum           
     1772 clustered Dregia_f9.Dregia_f11.mum           
     1960 clustered Dregia_f7.Dregia_f4.mum           
     1568 clustered Dregia_f6.Dregia_f17.mum           
     1948 clustered Dregia_f15.Dregia_f10.mum           
     2099 clustered Dregia_f9.Dregia_f16.mum           
     1795 clustered Dregia_f6.Dregia_f5.mum           
     2520 clustered Dregia_f15.Dregia_f13.mum           
     2214 clustered Dregia_f16.Dregia_f1.mum           
     1490 clustered Dregia_f2.Dregia_f17.mum           
     2130 clustered Dregia_f5.Dregia_f3.mum           
     1609 clustered Dregia_f7.Dregia_f2.mum           
     1982 clustered Dregia_f7.Dregia_f5.mum           
     2385 clustered Dregia_f3.Dregia_f14.mum           
     2006 clustered Dregia_f5.Dregia_f11.mum           
     2739 clustered Dregia_f3.Dregia_f16.mum           
     2122 clustered Dregia_f5.Dregia_f4.mum           
     3151 clustered Dregia_f14.Dregia_f13.mum           
     2093 clustered Dregia_f2.Dregia_f13.mum           
     2292 clustered Dregia_f14.Dregia_f1.mum           
     2167 clustered Dregia_f7.Dregia_f16.mum           
     1897 clustered Dregia_f7.Dregia_f3.mum           
     2142 clustered Dregia_f4.Dregia_f11.mum           
     2643 clustered Dregia_f17.Dregia_f16.mum           
     2170 clustered Dregia_f3.Dregia_f10.mum           
     2244 clustered Dregia_f13.Dregia_f10.mum           
     2439 clustered Dregia_f17.Dregia_f15.mum           
     2138 clustered Dregia_f17.Dregia_f13.mum           
     2055 clustered Dregia_f5.Dregia_f1.mum           
     1892 clustered Dregia_f9.Dregia_f3.mum           
     1861 clustered Dregia_f10.Dregia_f1.mum           
     2190 clustered Dregia_f8.Dregia_f12.mum           
     1645 clustered Dregia_f2.Dregia_f12.mum           
     2091 clustered Dregia_f4.Dregia_f15.mum           
     2187 clustered Dregia_f9.Dregia_f14.mum           
     1702 clustered Dregia_f6.Dregia_f13.mum           
     2047 clustered Dregia_f7.Dregia_f12.mum           
     2197 clustered Dregia_f9.Dregia_f12.mum           
     1837 clustered Dregia_f7.Dregia_f17.mum           
     2334 clustered Dregia_f14.Dregia_f10.mum           
     1729 clustered Dregia_f2.Dregia_f16.mum           
     2211 clustered Dregia_f3.Dregia_f12.mum           
     2866 clustered Dregia_f4.Dregia_f16.mum           
     2217 clustered Dregia_f4.Dregia_f13.mum           
     1980 clustered Dregia_f9.Dregia_f15.mum           
     1498 clustered Dregia_f2.Dregia_f15.mum           
     2212 clustered Dregia_f12.Dregia_f1.mum           
     1652 clustered Dregia_f11.Dregia_f1.mum           
     1855 clustered Dregia_f9.Dregia_f17.mum           
     1894 clustered Dregia_f7.Dregia_f15.mum           
     1963 clustered Dregia_f15.Dregia_f1.mum           
     1894 clustered Dregia_f7.Dregia_f11.mum           
     2819 clustered Dregia_f12.Dregia_f10.mum           
     2192 clustered Dregia_f8.Dregia_f16.mum           
     1830 clustered Dregia_f7.Dregia_f10.mum           
     1521 clustered Dregia_f6.Dregia_f1.mum           
     1926 clustered Dregia_f4.Dregia_f2.mum           
     2237 clustered Dregia_f9.Dregia_f8.mum           
     1935 clustered Dregia_f8.Dregia_f4.mum           
     1494 clustered Dregia_f6.Dregia_f2.mum           
     2069 clustered Dregia_f8.Dregia_f15.mum           
     2279 clustered Dregia_f5.Dregia_f12.mum           
     2824 clustered Dregia_f12.Dregia_f11.mum           
     2270 clustered Dregia_f5.Dregia_f16.mum           
     1950 clustered Dregia_f8.Dregia_f11.mum           
     1798 clustered Dregia_f9.Dregia_f10.mum           
     2170 clustered Dregia_f3.Dregia_f13.mum           
     2192 clustered Dregia_f16.Dregia_f10.mum           
     1936 clustered Dregia_f7.Dregia_f13.mum           
     2350 clustered Dregia_f5.Dregia_f14.mum           
     1758 clustered Dregia_f9.Dregia_f6.mum           
     1895 clustered Dregia_f15.Dregia_f11.mum           
     2517 clustered Dregia_f16.Dregia_f12.mum           
     2260 clustered Dregia_f17.Dregia_f14.mum           
     3010 clustered Dregia_f16.Dregia_f15.mum           
     1856 clustered Dregia_f8.Dregia_f1.mum           
     2497 clustered Dregia_f4.Dregia_f14.mum           
     2085 clustered Dregia_f4.Dregia_f1.mum           
     1990 clustered Dregia_f9.Dregia_f13.mum           
     1526 clustered Dregia_f6.Dregia_f11.mum           
     2498 clustered Dregia_f14.Dregia_f11.mum           
     1921 clustered Dregia_f17.Dregia_f11.mum           
     1903 clustered Dregia_f11.Dregia_f10.mum           
     2995 clustered Dregia_f5.Dregia_f17.mum           
     1797 clustered Dregia_f8.Dregia_f10.mum           
     1468 clustered Dregia_f2.Dregia_f10.mum           
     2183 clustered Dregia_f17.Dregia_f12.mum           
     1872 clustered Dregia_f6.Dregia_f16.mum           
     1769 clustered Dregia_f8.Dregia_f2.mum           
     1834 clustered Dregia_f6.Dregia_f12.mum           
     2036 clustered Dregia_f8.Dregia_f5.mum           
      809 clustered self.Dregia_f5.mum           
      681 clustered self.Dregia_f4.mum           
      561 clustered self.Dregia_f11.mum           
      659 clustered self.Dregia_f3.mum           
      509 clustered self.Dregia_f9.mum           
      713 clustered self.Dregia_f12.mum           
      727 clustered self.Dregia_f14.mum           
      688 clustered self.Dregia_f13.mum           
      381 clustered self.Dregia_f2.mum           
      626 clustered self.Dregia_f15.mum           
      790 clustered self.Dregia_f16.mum           
      553 clustered self.Dregia_f10.mum           
      479 clustered self.Dregia_f6.mum           
      476 clustered self.Dregia_f7.mum           
      571 clustered self.Dregia_f1.mum           
      551 clustered self.Dregia_f17.mum           
      615 clustered self.Dregia_f8.mum           
   294849 Total cluster hits              
Filter hits
    94747 for Dregia           
    96578 for Dregia           
    52303 Filtered hits to save           
Save results
   Save filtered hits
   Create and save hitNum
Could not execute: insert into pseudo_hits (select 0, hitnum, pair_idx,proj1_idx,proj2_idx,grp2_idx,grp1_idx,evalue,pctid,score,strand,start2,end2,start1,end1,target_seq,query_seq,gene_overlap,countpct,cvgpct,idx,annot2_idx,annot1_idx,runnum, runsize  from pseudo_hits where pair_idx=65 and refidx=0 and start1 != start2 and end1 != end2)
Error: add mirror hits
Data truncation: Incorrect integer value: '+/+' for column 'start1' at row 1

**Comment by dabitz** [comment]
07-Jul-23 13:57:05
Error: add mirror hits

com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect integer value: '+/+' for column 'start1' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2983)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Statement.executeUpdate(Statement.java:1402)
	at com.mysql.jdbc.Statement.executeUpdate(Statement.java:1317)
	at database.DBAbsUser.executeUpdate(DBAbsUser.java:95)
	at backend.AnchorsMain.addMirroredHits(AnchorsMain.java:712)
	at backend.AnchorsMain.saveAllResults(AnchorsMain.java:600)
	at backend.AnchorsMain.run(AnchorsMain.java:95)
	at backend.AlignProjs$2.run(AlignProjs.java:120)

**Comment by csoderlund** [comment]
Are you using v5.4.3 with an older database? If so, remove the database and reload. Please let me know if that does not fix it
